# Generated by Django 5.1.1 on 2024-10-17 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsecundaria', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='frase',
            options={'verbose_name': 'Frase', 'verbose_name_plural': 'frases'},
        ),
    ]
