# Generated by Django 5.1.1 on 2024-10-17 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appsecundaria', '0002_alter_frase_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumnot',
            options={'verbose_name': 'Alumno', 'verbose_name_plural': 'Alumnos'},
        ),
        migrations.AlterModelTable(
            name='alumnot',
            table='Alumnos',
        ),
    ]
